### ISSUE TITLE
Question: How to use your blocks?

### ISSUE THREAD

**Issue by szepeviktor** [mertJF/tailblocks#14]
Hello! I'm brand new to CSS-in-JS and Tailwind.

How does one use your blocks? Copy & paste?

**Comment by aryavb** [comment]
@szepeviktor So essentially, Tailwind allows developers/designers to perform most CSS tasks using class names rather than having the write the CSS yourself. 

For example, instead of doing the following:
```
<body>
  <div class="box">Hello, World!</div>
</body>
<style>
  .box {
    border: 8px solid gray;
  }
</style>
```
you would do this:
```
<body>
  <div class="border-8 border-gray-600">Hello, World!</div>
</body>
```

There's a few ways you can setup Tailwind in your project: linking from a CDN (not recommended) or installing Tailwind and PurgeCSS with NPM (recommended).

This project gives your examples of using Tailwind's utility classes. To use the site:
1. Find a template that you need with the icons in the left sidebar.
2. Select the color scheme you want in the top toolbar.
3. Select whether you want a dark or light version in the top toolbar.
4. Click "View Code" in the top toolbar.
5. Copy the code into your .html file, into the <template> tags of your Vue component, or into the render method of your React app, etc.

**Comment by szepeviktor** [comment]
Thank you!
I suspected copy & paste.
