### ISSUE TITLE
Dark Mode Toggle

### ISSUE THREAD

**Issue by Snooz3** [mertJF/tailblocks#23]
Is there a way to copy the code for this per page? Or how did you implement it

**Comment by aryavb** [comment]
@Snooz3 I think I somewhat understand your question. For every icon, there is both a dark and light version. To access the light version, switch the toggle where it shows a sun, press "View Code" and then "Copy To Clipboard." Then to get to the dark version, switch the toggle, and press "Copy To Clipboard." At this time, it is up to you to implement the dark/light mode toggle if that's what you're asking; there are many tutorials online that can help. I believe the authors' intention was to make quick template markup rather than a UI component library.

**Comment by azzamsa** [comment]
maybe what @Snooz3 means is how to copy this button.

![image](https://user-images.githubusercontent.com/17734314/91259431-bbcc6000-e798-11ea-9211-198851b8e045.png)

---

> Yeah it definitely would be nice to have a tailwind example of the toggle if possible. Otherwise you could dig through the source code to try and recreate it

@eric-hc, I am looking for the same thing.
